# Generated by Django 5.2.11 on 2026-05-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="case",
            field=models.TextField(blank=True, null=True),
        ),
    ]
