# Generated by Django 5.2.11 on 2026-05-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0002_bloodrequest_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lahore", "Lahore"),
                    ("Faisalabad", "Faisalabad"),
                    ("Rawalpindi", "Rawalpindi"),
                    ("Multan", "Multan"),
                    ("Gujranwala", "Gujranwala"),
                    ("Sialkot", "Sialkot"),
                    ("Sargodha", "Sargodha"),
                    ("Bahawalpur", "Bahawalpur"),
                    ("Dera Ghazi Khan", "Dera Ghazi Khan"),
                    ("Sheikhupura", "Sheikhupura"),
                    ("Karachi", "Karachi"),
                    ("Hyderabad", "Hyderabad"),
                    ("Sukkur", "Sukkur"),
                    ("Larkana", "Larkana"),
                    ("Mirpurkhas", "Mirpurkhas"),
                    ("Nawabshah", "Nawabshah"),
                    ("Peshawar", "Peshawar"),
                    ("Mardan", "Mardan"),
                    ("Swat", "Swat"),
                    ("Abbottabad", "Abbottabad"),
                    ("Mingora", "Mingora"),
                    ("Kohat", "Kohat"),
                    ("Dera Ismail Khan", "Dera Ismail Khan"),
                    ("Quetta", "Quetta"),
                    ("Gwadar", "Gwadar"),
                    ("Turbat", "Turbat"),
                    ("Sibi", "Sibi"),
                    ("Loralai", "Loralai"),
                    ("Islamabad", "Islamabad"),
                    ("Gilgit", "Gilgit"),
                    ("Skardu", "Skardu"),
                    ("Hunza", "Hunza"),
                    ("Muzaffarabad", "Muzaffarabad"),
                    ("Mirpur", "Mirpur"),
                    ("Rawalakot", "Rawalakot"),
                    ("Khushab", "Khushab"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="local_level",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Punjab", "Punjab"),
                    ("Sindh", "Sindh"),
                    ("Khyber Pakhtunkhwa", "Khyber Pakhtunkhwa"),
                    ("Balochistan", "Balochistan"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="required_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="required_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
