# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0002_bloodrequest_case"),
    ]

    operations = [
        # Fields already exist in initial migration
    ]
