# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0003_bloodrequest_district_bloodrequest_gender_and_more"),
    ]

    operations = [
        # Fields already configured correctly in current model
    ]
