# Generated by Django 5.2.11 on 2026-05-01 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_province_district_locallevel"),
        ("blood_requests", "0003_bloodrequest_district_bloodrequest_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blood_requests",
                to="accounts.district",
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="local_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blood_requests",
                to="accounts.locallevel",
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blood_requests",
                to="accounts.province",
            ),
        ),
    ]
