# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0004_alter_bloodrequest_district_and_more"),
    ]

    operations = [
        # Gender field already configured correctly
    ]
