# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0005_set_gender_default_and_make_required"),
    ]

    operations = [
        # Gender field already configured correctly
    ]
