# Generated by Django 5.2.11 on 2026-05-01 11:45

import django.db.models.deletion
from django.db import migrations, models


def convert_gender_to_foreign_key(apps, schema_editor):
    """Convert existing gender string values to foreign keys"""
    Gender = apps.get_model("accounts", "Gender")
    BloodRequest = apps.get_model("blood_requests", "BloodRequest")

    # Get gender objects
    gender_map = {g.name: g for g in Gender.objects.all()}

    # Convert existing gender values to foreign keys
    for request in BloodRequest.objects.all():
        if request.gender and isinstance(request.gender, str):
            gender_name = request.gender
            if gender_name in gender_map:
                request.gender = gender_map[gender_name]
                request.save(update_fields=["gender"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_gender"),
        ("blood_requests", "0005_set_gender_default_and_make_required"),
    ]

    operations = [
        migrations.RunPython(convert_gender_to_foreign_key, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="bloodrequest",
            name="gender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blood_requests",
                to="accounts.gender",
            ),
        ),
    ]
