# Generated by Django 5.2.11 on 2026-05-01 11:56

import django.db.models.deletion
from django.db import migrations, models


def convert_blood_group_to_foreign_key(apps, schema_editor):
    """Convert existing blood_group string values to foreign keys"""
    BloodGroup = apps.get_model("accounts", "BloodGroup")
    BloodRequest = apps.get_model("blood_requests", "BloodRequest")

    # Get blood group objects
    blood_group_map = {bg.name: bg for bg in BloodGroup.objects.all()}

    # Convert existing blood_group values to foreign keys
    for request in BloodRequest.objects.all():
        if request.blood_group and isinstance(request.blood_group, str):
            blood_group_name = request.blood_group
            if blood_group_name in blood_group_map:
                request.blood_group = blood_group_map[blood_group_name]
                request.save(update_fields=["blood_group"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_populate_blood_groups"),
        ("blood_requests", "0006_alter_bloodrequest_gender"),
    ]

    operations = [
        migrations.RunPython(convert_blood_group_to_foreign_key, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="bloodrequest",
            name="blood_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blood_requests",
                to="accounts.bloodgroup",
            ),
        ),
    ]
