# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0006_alter_bloodrequest_gender"),
    ]

    operations = [
        # Blood group field already configured correctly
    ]
