# Generated by Django 5.2.11 on 2026-05-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0007_alter_bloodrequest_blood_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodrequest",
            name="urgency_level",
        ),
    ]
