# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0007_alter_bloodrequest_blood_group"),
    ]

    operations = [
        # Urgency level field already removed from current model
    ]
