# Generated by Django 5.2.11 on 2026-05-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0008_remove_urgency_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodrequest",
            name="hospital_name",
        ),
    ]
