# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0008_remove_urgency_level"),
    ]

    operations = [
        # Hospital name field already removed from current model
    ]
