# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0009_remove_hospital_name"),
    ]

    operations = [
        # City field already removed from current model
    ]
