# Generated by Django 5.2.11 on 2026-05-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0009_remove_hospital_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodrequest",
            name="city",
        ),
    ]
