# Generated by Django 5.2.11 on 2026-05-05 12:40

from django.db import migrations, models

def convert_string_to_int(apps, schema_editor):
    """Convert existing string data to integer IDs"""
    BloodRequest = apps.get_model('blood_requests', 'BloodRequest')

    # Mapping dictionaries
    blood_group_map = {
        'A+': 1, 'A-': 2, 'B+': 3, 'B-': 4,
        'AB+': 5, 'AB-': 6, 'O+': 7, 'O-': 8
    }

    gender_map = {
        'Male': 1, 'Female': 2, 'Other': 3
    }

    province_map = {
        'Punjab': 1,
        'Sindh': 2,
        'Khyber Pakhtunkhwa': 3,
        'Balochistan': 4,
        'Gilgit Baltistan': 5,
        'Azad Kashmir': 6,
        'Islamabad Capital Territory': 7
    }

    for request in BloodRequest.objects.all():
        # Convert blood_group
        if request.blood_group in blood_group_map:
            request.blood_group = blood_group_map[request.blood_group]

        # Convert gender
        if request.gender in gender_map:
            request.gender = gender_map[request.gender]

        # Convert province
        if request.province in province_map:
            request.province = province_map[request.province]

        request.save()


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0010_remove_city"),
    ]

    operations = [
        # First convert existing data
        migrations.RunPython(convert_string_to_int, migrations.RunPython.noop),

        # Then alter the fields
        migrations.AlterField(
            model_name="bloodrequest",
            name="blood_group",
            field=models.IntegerField(
                choices=[
                    (1, "A+"),
                    (2, "A-"),
                    (3, "B+"),
                    (4, "B-"),
                    (5, "AB+"),
                    (6, "AB-"),
                    (7, "O+"),
                    (8, "O-"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "Male"), (2, "Female"), (3, "Other")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="province",
            field=models.IntegerField(
                choices=[
                    (1, "Punjab"),
                    (2, "Sindh"),
                    (3, "Khyber Pakhtunkhwa"),
                    (4, "Balochistan"),
                    (5, "Gilgit Baltistan"),
                    (6, "Azad Kashmir"),
                    (7, "Islamabad Capital Territory"),
                ],
                default=1,
            ),
        ),
    ]
