# Generated by Django 5.2.3 on 2026-05-06 16:37

from django.db import migrations, models


def convert_district_strings_to_integers(apps, schema_editor):
    """Convert existing string district names to integer IDs"""
    BloodRequest = apps.get_model("blood_requests", "BloodRequest")

    # District mapping (string name -> integer ID)
    district_mapping = {
        "Lahore": 1,
        "Karachi": 2,
        "Islamabad": 3,
        "Rawalpindi": 4,
        "Faisalabad": 5,
        "Multan": 6,
        "Peshawar": 7,
        "Quetta": 8,
        "Gilgit": 9,
        "Muzaffarabad": 10,
        "Sialkot": 11,
        "Gujranwala": 12,
        "Sargodha": 13,
        "Hyderabad": 14,
        "Sukkur": 15,
    }

    for request in BloodRequest.objects.all():
        if request.district and isinstance(request.district, str):
            # Convert string district to integer ID
            district_id = district_mapping.get(request.district.strip())
            if district_id:
                request.district = district_id
                request.save(update_fields=["district"])
            else:
                # If district not found in mapping, set to None
                request.district = None
                request.save(update_fields=["district"])


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0011_alter_bloodrequest_blood_group_and_more"),
    ]

    operations = [
        # Step 1: Add a temporary integer field
        migrations.AddField(
            model_name="bloodrequest",
            name="district_int",
            field=models.IntegerField(choices=[
                (1, "Lahore"),
                (2, "Karachi"),
                (3, "Islamabad"),
                (4, "Rawalpindi"),
                (5, "Faisalabad"),
                (6, "Multan"),
                (7, "Peshawar"),
                (8, "Quetta"),
                (9, "Gilgit"),
                (10, "Muzaffarabad"),
                (11, "Sialkot"),
                (12, "Gujranwala"),
                (13, "Sargodha"),
                (14, "Hyderabad"),
                (15, "Sukkur"),
            ], null=True, blank=True),
        ),
        # Step 2: Run data migration function
        migrations.RunPython(convert_district_strings_to_integers),
        # Step 3: Remove the old string field
        migrations.RemoveField(
            model_name="bloodrequest",
            name="district",
        ),
        # Step 4: Rename the new field to the original name
        migrations.RenameField(
            model_name="bloodrequest",
            old_name="district_int",
            new_name="district",
        ),
    ]
