# Generated by Django 5.2.3 on 2026-05-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0015_alter_bloodrequest_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="A+",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Male",
                max_length=10,
            ),
        ),
    ]
