# Generated by Django 5.2.3 on 2026-05-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0016_alter_bloodrequest_blood_group_and_more"),
    ]

    operations = [
        # Directly alter field types to CharField (string-based)
        # Note: This will lose existing data in these columns
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(
                max_length=5,
                choices=[
                    ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'),
                    ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')
                ],
                default='A+'
            ),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='gender',
            field=models.CharField(
                max_length=10,
                choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')],
                default='Male'
            ),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='province',
            field=models.CharField(
                max_length=50,
                choices=[
                    ('Punjab', 'Punjab'),
                    ('Sindh', 'Sindh'),
                    ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'),
                    ('Balochistan', 'Balochistan'),
                    ('Islamabad Capital Territory', 'Islamabad Capital Territory'),
                    ('Gilgit-Baltistan', 'Gilgit-Baltistan'),
                    ('Azad Jammu and Kashmir', 'Azad Jammu and Kashmir')
                ],
                default='Punjab'
            ),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
