# Generated by Django 5.2.11 on 2026-05-05 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.IntegerField(
                        help_text="Reference to the user account ID",
                        verbose_name="User ID",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the donor is currently available for blood donation",
                        verbose_name="Available for Donation",
                    ),
                ),
                (
                    "last_donation_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of the most recent blood donation",
                        null=True,
                        verbose_name="Last Donation Date",
                    ),
                ),
                (
                    "total_donations",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of blood donations made",
                        verbose_name="Total Donations",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Donor profile creation timestamp",
                        verbose_name="Created At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donor",
                "verbose_name_plural": "Donors",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="accounts_do_user_id_f113ce_idx"
                    ),
                    models.Index(
                        fields=["is_available"], name="accounts_do_is_avai_882abf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.IntegerField(
                        help_text="Reference to the user account ID",
                        verbose_name="User ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token for email verification",
                        unique=True,
                        verbose_name="Verification Token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Token creation timestamp",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the token has been used",
                        verbose_name="Used",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification",
                "verbose_name_plural": "Email Verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="accounts_em_token_21db79_idx"),
                    models.Index(
                        fields=["user_id", "is_used"],
                        name="accounts_em_user_id_84251d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.IntegerField(
                        help_text="Reference to the user account ID",
                        verbose_name="User ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token for password reset",
                        unique=True,
                        verbose_name="Reset Token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Token creation timestamp",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the token has been used",
                        verbose_name="Used",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset",
                "verbose_name_plural": "Password Resets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="accounts_pa_token_8f13bc_idx"),
                    models.Index(
                        fields=["user_id", "is_used"],
                        name="accounts_pa_user_id_f0b131_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User's complete name",
                        max_length=100,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Unique email address for login",
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Hashed password",
                        max_length=128,
                        verbose_name="Password",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact phone number",
                        max_length=15,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        help_text="User's gender",
                        max_length=10,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        help_text="User's province",
                        max_length=100,
                        null=True,
                        verbose_name="Province",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        help_text="User's district within province",
                        max_length=100,
                        null=True,
                        verbose_name="District",
                    ),
                ),
                (
                    "local_level",
                    models.CharField(
                        blank=True,
                        help_text="Specific area or locality",
                        max_length=200,
                        null=True,
                        verbose_name="Local Level",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="User's date of birth for age validation",
                        null=True,
                        verbose_name="Date of Birth",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        help_text="User's blood group",
                        max_length=3,
                        null=True,
                        verbose_name="Blood Group",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Account creation timestamp",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last update timestamp",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site",
                        verbose_name="Staff Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="accounts_my_email_28cc8a_idx"),
                    models.Index(
                        fields=["created_at"], name="accounts_my_created_140814_idx"
                    ),
                    models.Index(
                        fields=["blood_group"], name="accounts_my_blood_g_c790a9_idx"
                    ),
                ],
            },
        ),
    ]
