# Generated by Django 5.2.3 on 2026-05-15 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email address for authentication and contact",
                        max_length=255,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="User's first name",
                        max_length=150,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="User's last name",
                        max_length=150,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number (unique identifier)",
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site",
                        verbose_name="Staff Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the user account was created",
                        verbose_name="Date Joined",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the user was last updated",
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the donor is currently available for blood donation",
                        verbose_name="Available for Donation",
                    ),
                ),
                (
                    "last_donation_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of the most recent blood donation",
                        null=True,
                        verbose_name="Last Donation Date",
                    ),
                ),
                (
                    "total_donations",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of blood donations made",
                        verbose_name="Total Donations",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Donor profile creation timestamp",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donor",
                "verbose_name_plural": "Donors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token for email verification",
                        unique=True,
                        verbose_name="Verification Token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Token creation timestamp",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the token has been used",
                        verbose_name="Used",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification",
                "verbose_name_plural": "Email Verifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token for password reset",
                        unique=True,
                        verbose_name="Reset Token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Token creation timestamp",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the token has been used",
                        verbose_name="Used",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_resets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset",
                "verbose_name_plural": "Password Resets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact phone number",
                        max_length=15,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        help_text="User's gender",
                        max_length=10,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Punjab", "Punjab"),
                            ("Sindh", "Sindh"),
                            ("Khyber Pakhtunkhwa", "Khyber Pakhtunkhwa"),
                            ("Balochistan", "Balochistan"),
                            (
                                "Islamabad Capital Territory",
                                "Islamabad Capital Territory",
                            ),
                            ("Gilgit-Baltistan", "Gilgit-Baltistan"),
                            ("Azad Jammu and Kashmir", "Azad Jammu and Kashmir"),
                        ],
                        help_text="User's province",
                        max_length=100,
                        null=True,
                        verbose_name="Province",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Lahore", "Lahore"),
                            ("Faisalabad", "Faisalabad"),
                            ("Rawalpindi", "Rawalpindi"),
                            ("Multan", "Multan"),
                            ("Gujranwala", "Gujranwala"),
                            ("Sialkot", "Sialkot"),
                            ("Karachi", "Karachi"),
                            ("Hyderabad", "Hyderabad"),
                            ("Sukkur", "Sukkur"),
                            ("Peshawar", "Peshawar"),
                            ("Mardan", "Mardan"),
                            ("Quetta", "Quetta"),
                            ("Islamabad", "Islamabad"),
                            ("Other", "Other"),
                        ],
                        help_text="User's district within province",
                        max_length=100,
                        null=True,
                        verbose_name="District",
                    ),
                ),
                (
                    "local_level",
                    models.CharField(
                        blank=True,
                        help_text="Specific area or locality",
                        max_length=200,
                        null=True,
                        verbose_name="Local Level",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="User's date of birth for age validation",
                        null=True,
                        verbose_name="Date of Birth",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        help_text="User's blood group",
                        max_length=3,
                        null=True,
                        verbose_name="Blood Group",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Profile creation timestamp",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last update timestamp",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="accounts_cu_email_5ce40b_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["phone"], name="accounts_cu_phone_c30b3c_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["is_active"], name="accounts_cu_is_acti_2885e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donor",
            index=models.Index(fields=["user"], name="accounts_do_user_id_f113ce_idx"),
        ),
        migrations.AddIndex(
            model_name="donor",
            index=models.Index(
                fields=["is_available"], name="accounts_do_is_avai_882abf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(fields=["token"], name="accounts_em_token_21db79_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["user", "is_used"], name="accounts_em_user_id_84251d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordreset",
            index=models.Index(fields=["token"], name="accounts_pa_token_8f13bc_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordreset",
            index=models.Index(
                fields=["user", "is_used"], name="accounts_pa_user_id_f0b131_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["user"], name="accounts_us_user_id_806298_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["blood_group"], name="accounts_us_blood_g_6a7828_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["created_at"], name="accounts_us_created_70c995_idx"
            ),
        ),
    ]
