# Generated by Django 5.2.11 on 2026-04-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="city",
            field=models.CharField(max_length=100),
        ),
    ]
