# Generated by Django 5.2.3 on 2026-05-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="User's first name",
                max_length=150,
                verbose_name="First Name",
            ),
        ),
    ]
