# Generated by Django 5.2.11 on 2026-04-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_myuser_city"),
    ]

    operations = [
        # gender field already configured correctly in initial migration
    ]
