# Generated by Django 5.2.11 on 2026-04-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_myuser_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=6,
            ),
        ),
    ]
