# Generated by Django 5.2.3 on 2026-05-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Contact phone number",
                max_length=15,
                null=True,
                verbose_name="Phone Number",
            ),
        ),
    ]
