# Generated by Django 5.2.11 on 2026-04-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_myuser_gender"),
    ]

    operations = [
        # date_of_birth already exists in initial migration
        # role field doesn't exist in current model
    ]
