# Generated by Django 5.2.11 on 2026-04-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_myuser_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="role",
            field=models.CharField(default="user", max_length=20),
        ),
    ]
