# Generated by Django 5.2.11 on 2026-04-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_myuser_date_of_birth_myuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("donor", "Donor"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
    ]
