# Generated by Django 5.2.11 on 2026-04-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_myuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="last_name",
        ),
        migrations.AddField(
            model_name="myuser",
            name="full_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
