# Generated by Django 5.2.11 on 2026-04-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_myuser_role"),
    ]

    operations = [
        # full_name already exists in initial migration, no changes needed
    ]
