# Generated by Django 5.2.3 on 2026-04-29 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_myuser_first_name_remove_myuser_last_name_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        # All models and fields already exist in initial migration
        # This migration was for a previous version of the schema
    ]
