# Generated by Django 5.2.3 on 2026-04-29 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_myuser_first_name_remove_myuser_last_name_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token for email verification",
                        unique=True,
                        verbose_name="Verification Token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Token creation timestamp",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the token has been used",
                        verbose_name="Used",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification",
                "verbose_name_plural": "Email Verifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="donor",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Donor",
                "verbose_name_plural": "Donors",
            },
        ),
        migrations.AlterModelOptions(
            name="myuser",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="city",
        ),
        migrations.AddField(
            model_name="myuser",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lahore", "Lahore"),
                    ("Faisalabad", "Faisalabad"),
                    ("Rawalpindi", "Rawalpindi"),
                    ("Multan", "Multan"),
                    ("Gujranwala", "Gujranwala"),
                    ("Sialkot", "Sialkot"),
                    ("Sargodha", "Sargodha"),
                    ("Bahawalpur", "Bahawalpur"),
                    ("Dera Ghazi Khan", "Dera Ghazi Khan"),
                    ("Sheikhupura", "Sheikhupura"),
                    ("Karachi", "Karachi"),
                    ("Hyderabad", "Hyderabad"),
                    ("Sukkur", "Sukkur"),
                    ("Larkana", "Larkana"),
                    ("Mirpurkhas", "Mirpurkhas"),
                    ("Nawabshah", "Nawabshah"),
                    ("Peshawar", "Peshawar"),
                    ("Mardan", "Mardan"),
                    ("Swat", "Swat"),
                    ("Abbottabad", "Abbottabad"),
                    ("Mingora", "Mingora"),
                    ("Kohat", "Kohat"),
                    ("Dera Ismail Khan", "Dera Ismail Khan"),
                    ("Quetta", "Quetta"),
                    ("Gwadar", "Gwadar"),
                    ("Turbat", "Turbat"),
                    ("Sibi", "Sibi"),
                    ("Loralai", "Loralai"),
                    ("Islamabad", "Islamabad"),
                    ("Gilgit", "Gilgit"),
                    ("Skardu", "Skardu"),
                    ("Hunza", "Hunza"),
                    ("Muzaffarabad", "Muzaffarabad"),
                    ("Mirpur", "Mirpur"),
                    ("Rawalakot", "Rawalakot"),
                    ("Khushab", "Khushab"),
                ],
                default="",
                help_text="User's district within province",
                max_length=100,
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="myuser",
            name="local_level",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Specific area or locality",
                max_length=200,
                verbose_name="Local Level",
            ),
        ),
        migrations.AddField(
            model_name="myuser",
            name="province",
            field=models.CharField(default="Punjab", max_length=100),
        ),
        migrations.AlterField(
            model_name="donor",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                help_text="Donor's blood type",
                max_length=3,
                verbose_name="Blood Group",
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Donor profile creation timestamp",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Whether the donor is currently available for blood donation",
                verbose_name="Available for Donation",
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="last_donation_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the most recent blood donation",
                null=True,
                verbose_name="Last Donation Date",
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="total_donations",
            field=models.IntegerField(
                default=0,
                help_text="Total number of blood donations made",
                verbose_name="Total Donations",
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="user",
            field=models.OneToOneField(
                help_text="Reference to the user account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donor_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Account creation timestamp",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="User's date of birth for age validation",
                null=True,
                verbose_name="Date of Birth",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="email",
            field=models.EmailField(
                help_text="Unique email address for login",
                max_length=254,
                unique=True,
                verbose_name="Email Address",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="full_name",
            field=models.CharField(
                help_text="User's complete name",
                max_length=100,
                verbose_name="Full Name",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Other",
                help_text="User's gender",
                max_length=6,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site",
                verbose_name="Staff Status",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="password",
            field=models.CharField(
                help_text="Hashed password", max_length=128, verbose_name="Password"
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="phone",
            field=models.CharField(
                help_text="Contact phone number",
                max_length=15,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("donor", "Donor"),
                    ("admin", "Admin"),
                ],
                default="patient",
                help_text="User role: patient, donor, or admin",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last update timestamp",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddIndex(
            model_name="donor",
            index=models.Index(
                fields=["blood_group"], name="accounts_do_blood_g_47a6c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donor",
            index=models.Index(
                fields=["is_available"], name="accounts_do_is_avai_882abf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donor",
            index=models.Index(fields=["user"], name="accounts_do_user_id_f113ce_idx"),
        ),
        migrations.AddIndex(
            model_name="myuser",
            index=models.Index(fields=["email"], name="accounts_my_email_28cc8a_idx"),
        ),
        migrations.AddIndex(
            model_name="myuser",
            index=models.Index(
                fields=["province", "district"], name="accounts_my_provinc_faa4f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="myuser",
            index=models.Index(fields=["role"], name="accounts_my_role_55d5e7_idx"),
        ),
        migrations.AddIndex(
            model_name="myuser",
            index=models.Index(
                fields=["created_at"], name="accounts_my_created_140814_idx"
            ),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="user",
            field=models.ForeignKey(
                help_text="Reference to the user account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(fields=["token"], name="accounts_em_token_21db79_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["user", "is_used"], name="accounts_em_user_id_84251d_idx"
            ),
        ),
    ]
