# Generated by Django 5.2.11 on 2026-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_emailverification_alter_donor_options_and_more"),
    ]

    operations = [
        # Index and role field don't exist - province already configured correctly
    ]
