# Generated by Django 5.2.11 on 2026-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_emailverification_alter_donor_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="myuser",
            name="accounts_my_role_55d5e7_idx",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="role",
        ),
        migrations.AlterField(
            model_name="myuser",
            name="province",
            field=models.CharField(
                choices=[
                    ("Punjab", "Punjab"),
                    ("Sindh", "Sindh"),
                    ("Khyber Pakhtunkhwa", "Khyber Pakhtunkhwa"),
                    ("Balochistan", "Balochistan"),
                ],
                default="Punjab",
                help_text="User's province",
                max_length=100,
                verbose_name="Province",
            ),
        ),
    ]
