# Generated by Django 5.2.11 on 2026-04-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_myuser_accounts_my_role_55d5e7_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="full_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="User's complete name",
                max_length=100,
                verbose_name="Full Name",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Contact phone number",
                max_length=15,
                verbose_name="Phone Number",
            ),
        ),
    ]
