# Generated by Django 5.2.11 on 2026-04-30 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_myuser_full_name_alter_myuser_phone"),
    ]

    operations = [
        # PasswordReset table already exists in initial migration
    ]
