# Generated by Django 5.2.11 on 2026-05-01 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_passwordreset"),
    ]

    operations = [
        # Province, District, LocalLevel models and their fields already exist in MyUser model
    ]
