# Generated by Django 5.2.11 on 2026-05-01 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_passwordreset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="accounts.province",
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ["name"],
                "unique_together": {("province", "name")},
            },
        ),
        migrations.CreateModel(
            name="LocalLevel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_levels",
                        to="accounts.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Level",
                "verbose_name_plural": "Local Levels",
                "ordering": ["name"],
                "unique_together": {("district", "name")},
            },
        ),
    ]
