# Generated by Django 5.2.3 on 2026-05-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="role",
            field=models.CharField(
                choices=[("patient", "Patient"), ("donor", "Donor")],
                default="donor",
                help_text="User role: patient or donor",
                max_length=10,
                verbose_name="User Role",
            ),
        ),
    ]
