# Generated by Django 5.2.3 on 2026-05-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_myuser_role"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="email",
            field=models.EmailField(
                help_text="Email address (can be used for both donor and patient accounts)",
                max_length=254,
                verbose_name="Email Address",
            ),
        ),
        migrations.AddConstraint(
            model_name="myuser",
            constraint=models.UniqueConstraint(
                fields=("email", "role"),
                name="unique_email_role",
                violation_error_message="A user with this email and role already exists.",
            ),
        ),
    ]
