# Generated by Django 5.2.3 on 2026-05-11 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_myuser_email_myuser_unique_email_role"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        # Rename Donor model to LegacyDonor
        migrations.RenameModel(
            old_name='Donor',
            new_name='LegacyDonor',
        ),

        # Create Donor model
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(help_text="Donor's email address (unique across all donors)", max_length=254, unique=True, verbose_name='Email Address')),
                ('full_name', models.CharField(default='', help_text="Donor's complete name", max_length=100)),
                ('phone', models.CharField(default='', help_text='Contact phone number', max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', help_text="Donor's gender", max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', help_text="Donor's blood group", max_length=3)),
                ('province', models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan'), ('Islamabad Capital Territory', 'Islamabad Capital Territory'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Azad Jammu and Kashmir', 'Azad Jammu and Kashmir')], default='Punjab', help_text="Donor's province", max_length=100)),
                ('district', models.CharField(default='Lahore', help_text="Donor's district within province", max_length=100)),
                ('local_level', models.CharField(blank=True, help_text='Specific area or locality', max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="Donor's date of birth for age validation", null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Whether the donor is currently available for blood donation')),
                ('last_donation_date', models.DateField(blank=True, help_text='Date of the most recent blood donation', null=True)),
                ('total_donations', models.IntegerField(default=0, help_text='Total number of blood donations made')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this donor should be treated as active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the donor can log into this admin site')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this donor belongs to.', related_name='donor_set', related_query_name='donor', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this donor.', related_name='donor_set', related_query_name='donor', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['email'], name='accounts_donor_email_idx'),
                    models.Index(fields=['blood_group'], name='accounts_donor_blood_idx'),
                    models.Index(fields=['is_available'], name='accounts_donor_available_idx'),
                    models.Index(fields=['created_at'], name='accounts_donor_created_idx'),
                ],
                'abstract': False,
            },
        ),

        # Create Patient model
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(help_text="Patient's email address (unique across all patients)", max_length=254, unique=True, verbose_name='Email Address')),
                ('full_name', models.CharField(default='', help_text="Patient's complete name", max_length=100)),
                ('phone', models.CharField(default='', help_text='Contact phone number', max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text="Patient's gender", max_length=10, null=True)),
                ('province', models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan'), ('Islamabad Capital Territory', 'Islamabad Capital Territory'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Azad Jammu and Kashmir', 'Azad Jammu and Kashmir')], default='Punjab', help_text="Patient's province", max_length=100)),
                ('district', models.CharField(default='Lahore', help_text="Patient's district within province", max_length=100)),
                ('local_level', models.CharField(blank=True, help_text='Specific area or locality', max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="Patient's date of birth", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this patient should be treated as active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the patient can log into this admin site')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this patient belongs to.', related_name='patient_set', related_query_name='patient', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this patient.', related_name='patient_set', related_query_name='patient', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['email'], name='accounts_patient_email_idx'),
                    models.Index(fields=['created_at'], name='accounts_patient_created_idx'),
                ],
                'abstract': False,
            },
        ),

        # Create DonorEmailVerification model
        migrations.CreateModel(
            name='DonorEmailVerification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('donor_id', models.IntegerField(help_text='Reference to the donor account ID')),
            ],
            options={
                'verbose_name': 'Donor Email Verification',
                'verbose_name_plural': 'Donor Email Verifications',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['token'], name='accounts_donor_ev_token_idx'),
                    models.Index(fields=['donor_id', 'is_used'], name='accounts_donor_ev_donor_idx'),
                ],
            },
        ),

        # Create PatientEmailVerification model
        migrations.CreateModel(
            name='PatientEmailVerification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('patient_id', models.IntegerField(help_text='Reference to the patient account ID')),
            ],
            options={
                'verbose_name': 'Patient Email Verification',
                'verbose_name_plural': 'Patient Email Verifications',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['token'], name='accounts_patient_ev_token_idx'),
                    models.Index(fields=['patient_id', 'is_used'], name='accounts_patient_ev_patient_idx'),
                ],
            },
        ),

        # Create DonorPasswordReset model
        migrations.CreateModel(
            name='DonorPasswordReset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('donor_id', models.IntegerField(help_text='Reference to the donor account ID')),
            ],
            options={
                'verbose_name': 'Donor Password Reset',
                'verbose_name_plural': 'Donor Password Resets',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['token'], name='accounts_donor_pr_token_idx'),
                    models.Index(fields=['donor_id', 'is_used'], name='accounts_donor_pr_donor_idx'),
                ],
            },
        ),

        # Create PatientPasswordReset model
        migrations.CreateModel(
            name='PatientPasswordReset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('patient_id', models.IntegerField(help_text='Reference to the patient account ID')),
            ],
            options={
                'verbose_name': 'Patient Password Reset',
                'verbose_name_plural': 'Patient Password Resets',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['token'], name='accounts_patient_pr_token_idx'),
                    models.Index(fields=['patient_id', 'is_used'], name='accounts_patient_pr_patient_idx'),
                ],
            },
        ),
    ]
