# Generated by Django 5.2.11 on 2026-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=3, unique=True)),
            ],
            options={
                "verbose_name": "Blood Group",
                "verbose_name_plural": "Blood Groups",
                "ordering": ["name"],
            },
        ),
    ]
