# Generated by Django 5.2.11 on 2026-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_gender"),
    ]

    operations = [
        # Blood group choices already exist in MyUser model
    ]
