# Generated by Django 5.2.11 on 2026-05-01 12:55

import django.db.models.deletion
from django.db import migrations, models, connection


def convert_user_fields_to_foreignkeys(apps, schema_editor):
    """Convert varchar fields to ForeignKey relationships using raw SQL"""

    with connection.cursor() as cursor:
        # 1. Add new foreign key columns (temporary names)
        print("Adding new FK columns...")

        # Province FK
        cursor.execute("""
            ALTER TABLE accounts_myuser
            ADD COLUMN province_id_new INT NULL,
            ADD FOREIGN KEY (province_id_new) REFERENCES accounts_province(id);
        """)

        # District FK
        cursor.execute("""
            ALTER TABLE accounts_myuser
            ADD COLUMN district_id_new INT NULL,
            ADD FOREIGN KEY (district_id_new) REFERENCES accounts_district(id);
        """)

        # Local Level FK
        cursor.execute("""
            ALTER TABLE accounts_myuser
            ADD COLUMN local_level_id_new INT NULL,
            ADD FOREIGN KEY (local_level_id_new) REFERENCES accounts_locallevel(id);
        """)

        # Gender FK
        cursor.execute("""
            ALTER TABLE accounts_myuser
            ADD COLUMN gender_id_new INT NULL,
            ADD FOREIGN KEY (gender_id_new) REFERENCES accounts_gender(id);
        """)

        print("Populating new FK columns with data...")

        # 2. Populate the new FK columns based on existing varchar data
        # Province
        cursor.execute("""
            UPDATE accounts_myuser u
            SET u.province_id_new = (
                SELECT id FROM accounts_province p WHERE p.name = u.province
            )
            WHERE u.province IS NOT NULL AND u.province != '';
        """)

        # District
        cursor.execute("""
            UPDATE accounts_myuser u
            SET u.district_id_new = (
                SELECT d.id FROM accounts_district d
                WHERE d.name = u.district_id
            )
            WHERE u.district_id IS NOT NULL AND u.district_id != '';
        """)

        # Local Level
        cursor.execute("""
            UPDATE accounts_myuser u
            SET u.local_level_id_new = (
                SELECT ll.id FROM accounts_locallevel ll
                WHERE ll.name = u.local_level
            )
            WHERE u.local_level IS NOT NULL AND u.local_level != '';
        """)

        # Gender
        cursor.execute("""
            UPDATE accounts_myuser u
            SET u.gender_id_new = (
                SELECT g.id FROM accounts_gender g WHERE g.name = u.gender
            )
            WHERE u.gender IS NOT NULL AND u.gender != '';
        """)

        print("Dropping old varchar columns...")

        # 3. Drop the old varchar columns
        cursor.execute("ALTER TABLE accounts_myuser DROP COLUMN province;")
        cursor.execute("ALTER TABLE accounts_myuser DROP COLUMN district_id;")
        cursor.execute("ALTER TABLE accounts_myuser DROP COLUMN local_level;")
        cursor.execute("ALTER TABLE accounts_myuser DROP COLUMN gender;")

        print("Renaming new FK columns to original names...")

        # 4. Rename new columns to the original names
        cursor.execute("ALTER TABLE accounts_myuser CHANGE province_id_new province_id INT NULL;")
        cursor.execute("ALTER TABLE accounts_myuser CHANGE district_id_new district_id INT NULL;")
        cursor.execute("ALTER TABLE accounts_myuser CHANGE local_level_id_new local_level_id INT NULL;")
        cursor.execute("ALTER TABLE accounts_myuser CHANGE gender_id_new gender_id INT NULL;")

        print("Migration completed successfully!")


def reverse_conversion(apps, schema_editor):
    """Reverse the migration (not recommended but provided for safety)"""
    # This would revert back to varchar columns
    # In practice, this migration should not be reversed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_populate_blood_groups"),
    ]

    operations = [
        migrations.RunPython(convert_user_fields_to_foreignkeys, reverse_conversion),
    ]
