import '../models/donor_model.dart';

class DummyDonors {
  static List<Donor> getDonorsNearby(double userLat, double userLng) {
    // Dummy donors with various blood groups for testing
    return [
      Donor(
        id: '1',
        name: 'Ahmed Khan',
        email: 'ahmed.khan@example.com',
        bloodGroup: 'A+',
        province: 'Islamabad Capital Territory',
        district: 'Islamabad',
        localLevel: 'G-7 Markaz',
        phone: '+92-300-1234567',
        isAvailable: true,
        gender: 'Male',
        distance: 2.5,
        latitude: 33.6844,
        longitude: 73.0479,
        lastDonationDate: DateTime(2024, 3, 15),
        totalDonations: 8,
      ),
      Donor(
        id: '2',
        name: 'Fatima Ali',
        email: 'fatima.ali@example.com',
        bloodGroup: 'B+',
        province: 'Islamabad Capital Territory',
        district: 'Islamabad',
        localLevel: 'F-11 Markaz',
        phone: '+92-301-2345678',
        isAvailable: true,
        gender: 'Female',
        distance: 4.2,
        latitude: 33.6934,
        longitude: 73.0256,
        lastDonationDate: DateTime(2024, 2, 20),
        totalDonations: 5,
      ),
      Donor(
        id: '3',
        name: 'Hassan Raza',
        email: 'hassan.raza@example.com',
        bloodGroup: 'O+',
        province: 'Punjab',
        district: 'Rawalpindi',
        localLevel: 'Saddar',
        phone: '+92-302-3456789',
        isAvailable: true,
        gender: 'Male',
        distance: 8.7,
        latitude: 33.5651,
        longitude: 73.0169,
        lastDonationDate: DateTime(2024, 1, 10),
        totalDonations: 12,
      ),
      Donor(
        id: '4',
        name: 'Ayesha Khan',
        email: 'ayesha.khan@example.com',
        bloodGroup: 'AB+',
        province: 'Islamabad Capital Territory',
        district: 'Islamabad',
        localLevel: 'E-11 Markaz',
        phone: '+92-303-4567890',
        isAvailable: true,
        gender: 'Female',
        distance: 6.1,
        latitude: 33.7167,
        longitude: 72.9844,
        lastDonationDate: DateTime(2024, 3, 18),
        totalDonations: 3,
      ),
      Donor(
        id: '5',
        name: 'Usman Ahmed',
        email: 'usman.ahmed@example.com',
        bloodGroup: 'A-',
        province: 'Punjab',
        district: 'Rawalpindi',
        localLevel: 'Chaklala',
        phone: '+92-304-5678901',
        isAvailable: false,
        gender: 'Male',
        distance: 12.3,
        latitude: 33.6007,
        longitude: 73.0585,
        lastDonationDate: DateTime(2024, 2, 28),
        totalDonations: 6,
      ),
      Donor(
        id: '6',
        name: 'Sara Malik',
        email: 'sara.malik@example.com',
        bloodGroup: 'O-',
        province: 'Islamabad Capital Territory',
        district: 'Islamabad',
        localLevel: 'I-8 Markaz',
        phone: '+92-305-6789012',
        isAvailable: true,
        gender: 'Female',
        distance: 3.8,
        latitude: 33.7128,
        longitude: 73.0591,
        lastDonationDate: DateTime(2024, 3, 10),
        totalDonations: 9,
      ),
      Donor(
        id: '7',
        name: 'Bilal Hassan',
        email: 'bilal.hassan@example.com',
        bloodGroup: 'B-',
        province: 'Punjab',
        district: 'Rawalpindi',
        localLevel: 'Westridge',
        phone: '+92-306-7890123',
        isAvailable: true,
        gender: 'Male',
        distance: 15.6,
        latitude: 33.5489,
        longitude: 73.0272,
        lastDonationDate: DateTime(2024, 1, 25),
        totalDonations: 4,
      ),
      Donor(
        id: '8',
        name: 'Zainab Bibi',
        email: 'zainab.bibi@example.com',
        bloodGroup: 'A+',
        province: 'Punjab',
        district: 'Rawalpindi',
        localLevel: 'Raja Bazaar',
        phone: '+92-307-8901234',
        isAvailable: true,
        gender: 'Female',
        distance: 9.4,
        latitude: 33.5956,
        longitude: 73.0327,
        lastDonationDate: DateTime(2024, 3, 5),
        totalDonations: 7,
      ),
      Donor(
        id: '9',
        name: 'Muhammad Ali',
        email: 'muhammad.ali@example.com',
        bloodGroup: 'AB-',
        province: 'Islamabad Capital Territory',
        district: 'Islamabad',
        localLevel: 'D-12 Markaz',
        phone: '+92-308-9012345',
        isAvailable: true,
        gender: 'Male',
        distance: 18.2,
        latitude: 33.6644,
        longitude: 73.0023,
        lastDonationDate: DateTime(2024, 2, 15),
        totalDonations: 2,
      ),
      Donor(
        id: '10',
        name: 'Hira Shaheen',
        email: 'hira.shaheen@example.com',
        bloodGroup: 'O+',
        province: 'Punjab',
        district: 'Rawalpindi',
        localLevel: 'Satellite Town',
        phone: '+92-309-0123456',
        isAvailable: true,
        gender: 'Female',
        distance: 11.8,
        latitude: 33.5821,
        longitude: 73.0412,
        lastDonationDate: DateTime(2024, 3, 20),
        totalDonations: 6,
      ),
      Donor(
        id: '11',
        name: 'Kamran Akmal',
        email: 'kamran.akmal@example.com',
        bloodGroup: 'B+',
        province: 'Islamabad Capital Territory',
        district: 'Islamabad',
        localLevel: 'H-12 Markaz',
        phone: '+92-310-1234567',
        isAvailable: true,
        gender: 'Male',
        distance: 7.3,
        latitude: 33.7012,
        longitude: 73.0334,
        lastDonationDate: DateTime(2024, 1, 30),
        totalDonations: 10,
      ),
      Donor(
        id: '12',
        name: 'Sana Mirza',
        email: 'sana.mirza@example.com',
        bloodGroup: 'A-',
        province: 'Islamabad Capital Territory',
        district: 'Islamabad',
        localLevel: 'G-10 Markaz',
        phone: '+92-311-2345678',
        isAvailable: false,
        gender: 'Female',
        distance: 5.5,
        latitude: 33.6889,
        longitude: 73.0612,
        lastDonationDate: DateTime(2024, 3, 1),
        totalDonations: 3,
      ),
    ];
  }
}
