import '../models/donor_model.dart';

class MockDonorData {
  static List<Donor> getMockDonors() {
    return [
      // Islamabad Capital Territory
      Donor(
        id: '1',
        name: 'Ahmed Khan',
        bloodGroup: 'A+',
        province: 'Islamabad',
        district: 'Islamabad',
        localLevel: 'G-7 Markaz',
        phone: '+92-300-1234567',
        email: 'ahmed.khan@example.com',
        lastDonationDate: DateTime(2024, 3, 15),
        totalDonations: 8,
        isAvailable: true,
        gender: 'Male',
        distance: 2.5,
        latitude: 33.6844,
        longitude: 73.0479,
      ),
      Donor(
        id: '2',
        name: 'Fatima Ali',
        bloodGroup: 'B+',
        province: 'Islamabad',
        district: 'Islamabad',
        localLevel: 'F-11 Markaz',
        phone: '+92-301-2345678',
        email: 'fatima.ali@example.com',
        lastDonationDate: DateTime(2024, 2, 20),
        totalDonations: 5,
        isAvailable: true,
        gender: 'Female',
        distance: 4.2,
        latitude: 33.6934,
        longitude: 73.0256,
      ),
      Donor(
        id: '3',
        name: 'Hassan Raza',
        bloodGroup: 'O+',
        province: 'Punjab',
        district: 'Rawalpindi',
        localLevel: 'Saddar',
        phone: '+92-302-3456789',
        email: 'hassan.raza@example.com',
        lastDonationDate: DateTime(2024, 1, 10),
        totalDonations: 12,
        isAvailable: false,
        gender: 'Male',
        distance: 6.8,
        latitude: 33.5651,
        longitude: 73.0169,
      ),
      Donor(
        id: '4',
        name: 'Ayesha Siddiqui',
        bloodGroup: 'A+',
        province: 'Punjab',
        district: 'Rawalpindi',
        localLevel: 'Chaklala',
        phone: '+92-303-4567890',
        email: 'ayesha.siddiqui@example.com',
        lastDonationDate: DateTime(2024, 3, 18),
        totalDonations: 2,
        isAvailable: true,
        gender: 'Female',
        distance: 3.2,
        latitude: 33.5986,
        longitude: 73.0425,
      ),
      Donor(
        id: '5',
        name: 'Muhammad Bilal',
        bloodGroup: 'O+',
        province: 'Punjab',
        district: 'Rawalpindi',
        localLevel: 'Westridge',
        phone: '+92-304-5678901',
        email: 'bilal.muhammad@example.com',
        lastDonationDate: DateTime(2023, 10, 15),
        totalDonations: 10,
        isAvailable: true,
        gender: 'Male',
        distance: 5.5,
        latitude: 33.5872,
        longitude: 73.0215,
      ),
      Donor(
        id: '6',
        name: 'Zainab Ahmed',
        bloodGroup: 'A-',
        province: 'Punjab',
        district: 'Rawalpindi',
        localLevel: 'Lal Kurti',
        phone: '+92-305-6789012',
        email: 'zainab.ahmed@example.com',
        lastDonationDate: DateTime(2024, 2, 10),
        totalDonations: 6,
        isAvailable: false,
        gender: 'Female',
        distance: 4.8,
        latitude: 33.5748,
        longitude: 73.0089,
      ),

      // Punjab Province
      Donor(
        id: '7',
        name: 'Ali Hassan',
        bloodGroup: 'AB+',
        province: 'Punjab',
        district: 'Lahore',
        localLevel: 'Gulberg',
        phone: '+92-321-1234567',
        email: 'ali.hassan@example.com',
        lastDonationDate: DateTime(2023, 12, 5),
        totalDonations: 3,
        isAvailable: true,
        gender: 'Male',
        distance: 280.0,
        latitude: 31.5204,
        longitude: 74.3587,
      ),
      Donor(
        id: '8',
        name: 'Maryam Khan',
        bloodGroup: 'A-',
        province: 'Punjab',
        district: 'Faisalabad',
        localLevel: 'Sadar',
        phone: '+92-322-2345678',
        email: 'maryam.khan@example.com',
        lastDonationDate: DateTime(2024, 3, 1),
        totalDonations: 7,
        isAvailable: true,
        gender: 'Female',
        distance: 350.0,
        latitude: 31.4491,
        longitude: 73.1047,
      ),
      Donor(
        id: '9',
        name: 'Usman Malik',
        bloodGroup: 'AB+',
        province: 'Punjab',
        district: 'Multan',
        localLevel: 'Cantonment',
        phone: '+92-323-4567890',
        email: 'usman.malik@example.com',
        lastDonationDate: DateTime(2024, 3, 12),
        totalDonations: 3,
        isAvailable: true,
        gender: 'Male',
        distance: 520.0,
        latitude: 30.1992,
        longitude: 71.4687,
      ),
      Donor(
        id: '10',
        name: 'Hira Nawaz',
        bloodGroup: 'B-',
        province: 'Punjab',
        district: 'Sialkot',
        localLevel: 'Sadr',
        phone: '+92-324-5678901',
        email: 'hira.nawaz@example.com',
        lastDonationDate: DateTime(2024, 2, 15),
        totalDonations: 4,
        isAvailable: true,
        gender: 'Female',
        distance: 380.0,
        latitude: 32.4936,
        longitude: 74.5299,
      ),
      Donor(
        id: '11',
        name: 'Saad Tariq',
        bloodGroup: 'O-',
        province: 'Punjab',
        district: 'Gujranwala',
        localLevel: 'Satellite Town',
        phone: '+92-325-6789012',
        email: 'saad.tariq@example.com',
        lastDonationDate: DateTime(2023, 11, 20),
        totalDonations: 9,
        isAvailable: true,
        gender: 'Male',
        distance: 320.0,
        latitude: 32.1607,
        longitude: 74.1883,
      ),
      Donor(
        id: '12',
        name: 'Sana Rasheed',
        bloodGroup: 'A+',
        province: 'Punjab',
        district: 'Sargodha',
        localLevel: 'University Road',
        phone: '+92-326-7890123',
        email: 'sana.rasheed@example.com',
        lastDonationDate: DateTime(2024, 3, 10),
        totalDonations: 6,
        isAvailable: true,
        gender: 'Female',
        distance: 280.0,
        latitude: 32.0746,
        longitude: 72.6797,
      ),
      Donor(
        id: '13',
        name: 'Faraz Ahmed',
        bloodGroup: 'B+',
        province: 'Punjab',
        district: 'Bahawalpur',
        localLevel: 'Model Town',
        phone: '+92-327-8901234',
        email: 'faraz.ahmed@example.com',
        lastDonationDate: DateTime(2024, 1, 25),
        totalDonations: 8,
        isAvailable: false,
        gender: 'Male',
        distance: 620.0,
        latitude: 29.3544,
        longitude: 71.6911,
      ),
      Donor(
        id: '14',
        name: 'Khadija Ashraf',
        bloodGroup: 'B+',
        province: 'Punjab',
        district: 'DG Khan',
        localLevel: 'City Area',
        phone: '+92-328-9012345',
        email: 'khadija.ashraf@example.com',
        lastDonationDate: DateTime(2024, 3, 5),
        totalDonations: 4,
        isAvailable: true,
        gender: 'Female',
        distance: 580.0,
        latitude: 30.3056,
        longitude: 70.6787,
      ),

      // Sindh Province
      Donor(
        id: '15',
        name: 'Rashid Hussain',
        bloodGroup: 'AB-',
        province: 'Sindh',
        district: 'Karachi',
        localLevel: 'Clifton',
        phone: '+92-331-1234567',
        email: 'rashid.hussain@example.com',
        lastDonationDate: DateTime(2024, 2, 28),
        totalDonations: 5,
        isAvailable: true,
        gender: 'Male',
        distance: 1420.0,
        latitude: 24.8561,
        longitude: 67.0011,
      ),
      Donor(
        id: '16',
        name: 'Sadia Javed',
        bloodGroup: 'A+',
        province: 'Sindh',
        district: 'Karachi',
        localLevel: 'DHA Phase 6',
        phone: '+92-332-2345678',
        email: 'sadia.javed@example.com',
        lastDonationDate: DateTime(2024, 3, 8),
        totalDonations: 6,
        isAvailable: true,
        gender: 'Female',
        distance: 1415.0,
        latitude: 24.8257,
        longitude: 67.0601,
      ),
      Donor(
        id: '17',
        name: 'Imran Shah',
        bloodGroup: 'O+',
        province: 'Sindh',
        district: 'Hyderabad',
        localLevel: 'Qasimabad',
        phone: '+92-333-3456789',
        email: 'imran.shah@example.com',
        lastDonationDate: DateTime(2024, 1, 15),
        totalDonations: 11,
        isAvailable: true,
        gender: 'Male',
        distance: 1240.0,
        latitude: 25.3805,
        longitude: 68.3546,
      ),
      Donor(
        id: '18',
        name: 'Nida Kazmi',
        bloodGroup: 'B+',
        province: 'Sindh',
        district: 'Sukkur',
        localLevel: 'Civil Lines',
        phone: '+92-334-4567890',
        email: 'nida.kazmi@example.com',
        lastDonationDate: DateTime(2023, 12, 20),
        totalDonations: 7,
        isAvailable: false,
        gender: 'Female',
        distance: 980.0,
        latitude: 27.6944,
        longitude: 68.8573,
      ),
      Donor(
        id: '19',
        name: 'Arif Memon',
        bloodGroup: 'AB+',
        province: 'Sindh',
        district: 'Larkana',
        localLevel: 'Station Road',
        phone: '+92-335-5678901',
        email: 'arif.memon@example.com',
        lastDonationDate: DateTime(2024, 2, 22),
        totalDonations: 4,
        isAvailable: true,
        gender: 'Male',
        distance: 920.0,
        latitude: 27.5588,
        longitude: 68.2133,
      ),

      // Khyber Pakhtunkhwa (KPK)
      Donor(
        id: '20',
        name: 'Kashifullah Khan',
        bloodGroup: 'A-',
        province: 'KPK',
        district: 'Peshawar',
        localLevel: 'University Town',
        phone: '+92-341-1234567',
        email: 'kashifullah.khan@example.com',
        lastDonationDate: DateTime(2024, 3, 2),
        totalDonations: 8,
        isAvailable: true,
        gender: 'Male',
        distance: 180.0,
        latitude: 34.0128,
        longitude: 71.5725,
      ),
      Donor(
        id: '21',
        name: 'Gulalai Sher',
        bloodGroup: 'O+',
        province: 'KPK',
        district: 'Mardan',
        localLevel: 'Kutchery Road',
        phone: '+92-342-2345678',
        email: 'gulalai.sher@example.com',
        lastDonationDate: DateTime(2024, 1, 28),
        totalDonations: 5,
        isAvailable: true,
        gender: 'Female',
        distance: 230.0,
        latitude: 34.1148,
        longitude: 72.0457,
      ),
      Donor(
        id: '22',
        name: 'Zahid Afridi',
        bloodGroup: 'B+',
        province: 'KPK',
        district: 'Swat',
        localLevel: 'Mingora',
        phone: '+92-343-3456789',
        email: 'zahid.afridi@example.com',
        lastDonationDate: DateTime(2023, 11, 10),
        totalDonations: 9,
        isAvailable: true,
        gender: 'Male',
        distance: 260.0,
        latitude: 34.7694,
        longitude: 72.3629,
      ),
      Donor(
        id: '23',
        name: 'Maria Khan',
        bloodGroup: 'A+',
        province: 'KPK',
        district: 'Abbottabad',
        localLevel: 'Mandal',
        phone: '+92-344-4567890',
        email: 'maria.khan@example.com',
        lastDonationDate: DateTime(2024, 3, 14),
        totalDonations: 3,
        isAvailable: true,
        gender: 'Female',
        distance: 150.0,
        latitude: 34.1688,
        longitude: 73.2215,
      ),
      Donor(
        id: '24',
        name: 'Jamaluddin',
        bloodGroup: 'B-',
        province: 'KPK',
        district: 'Mansehra',
        localLevel: 'City Center',
        phone: '+92-345-5678901',
        email: 'jamaluddin@example.com',
        lastDonationDate: DateTime(2024, 2, 8),
        totalDonations: 6,
        isAvailable: false,
        gender: 'Male',
        distance: 170.0,
        latitude: 34.3303,
        longitude: 73.1967,
      ),

      // Balochistan Province
      Donor(
        id: '25',
        name: 'Abdul Rehman',
        bloodGroup: 'O+',
        province: 'Balochistan',
        district: 'Quetta',
        localLevel: 'Jinnah Road',
        phone: '+92-351-1234567',
        email: 'abdul.rehman@example.com',
        lastDonationDate: DateTime(2024, 3, 6),
        totalDonations: 7,
        isAvailable: true,
        gender: 'Male',
        distance: 920.0,
        latitude: 30.1834,
        longitude: 66.9987,
      ),
      Donor(
        id: '26',
        name: 'Nazia Baloch',
        bloodGroup: 'A+',
        province: 'Balochistan',
        district: 'Gwadar',
        localLevel: 'Marine Drive',
        phone: '+92-352-2345678',
        email: 'nazia.baloch@example.com',
        lastDonationDate: DateTime(2024, 2, 18),
        totalDonations: 4,
        isAvailable: true,
        gender: 'Female',
        distance: 1520.0,
        latitude: 25.2299,
        longitude: 62.3186,
      ),
      Donor(
        id: '27',
        name: 'Sajid Dashti',
        bloodGroup: 'B+',
        province: 'Balochistan',
        district: 'Turbat',
        localLevel: 'City Center',
        phone: '+92-353-3456789',
        email: 'sajid.dashti@example.com',
        lastDonationDate: DateTime(2023, 12, 12),
        totalDonations: 5,
        isAvailable: true,
        gender: 'Male',
        distance: 1320.0,
        latitude: 26.0015,
        longitude: 63.0460,
      ),
      Donor(
        id: '28',
        name: 'Gulzar Bugti',
        bloodGroup: 'AB-',
        province: 'Balochistan',
        district: 'Sibi',
        localLevel: 'Civil Lines',
        phone: '+92-354-4567890',
        email: 'gulzar.bugti@example.com',
        lastDonationDate: DateTime(2024, 3, 16),
        totalDonations: 2,
        isAvailable: true,
        gender: 'Male',
        distance: 880.0,
        latitude: 29.5584,
        longitude: 67.8779,
      ),
      Donor(
        id: '29',
        name: 'Saba Raisani',
        bloodGroup: 'O-',
        province: 'Balochistan',
        district: 'Loralai',
        localLevel: 'Cantonment',
        phone: '+92-355-5678901',
        email: 'saba.raisani@example.com',
        lastDonationDate: DateTime(2024, 1, 22),
        totalDonations: 8,
        isAvailable: true,
        gender: 'Female',
        distance: 750.0,
        latitude: 30.3638,
        longitude: 68.5947,
      ),
      Donor(
        id: '30',
        name: 'Asfand Yar',
        bloodGroup: 'A+',
        province: 'Balochistan',
        district: 'Zhob',
        localLevel: 'City Area',
        phone: '+92-356-6789012',
        email: 'asfand.yar@example.com',
        lastDonationDate: DateTime(2024, 2, 28),
        totalDonations: 6,
        isAvailable: false,
        gender: 'Male',
        distance: 620.0,
        latitude: 31.3413,
        longitude: 69.4643,
      ),
    ];
  }

  // Get all unique blood groups
  static List<String> getBloodGroups() {
    return ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
  }

  // Get all unique provinces (matching backend)
  static List<String> getProvinces() {
    return [
      'Punjab',
      'Sindh',
      'Khyber Pakhtunkhwa',
      'Balochistan',
    ];
  }

  // Get districts by province (matching backend model)
  static List<String> getDistricts(String province) {
    switch (province) {
      case 'Punjab':
        return [
          'Lahore',
          'Faisalabad',
          'Rawalpindi',
          'Multan',
          'Gujranwala',
          'Sialkot',
          'Sargodha',
          'Bahawalpur',
          'Dera Ghazi Khan',
          'Sheikhupura',
          'Khushab',
        ];
      case 'Sindh':
        return [
          'Karachi',
          'Hyderabad',
          'Sukkur',
          'Larkana',
          'Mirpurkhas',
          'Nawabshah',
        ];
      case 'Khyber Pakhtunkhwa':
        return [
          'Peshawar',
          'Mardan',
          'Swat',
          'Abbottabad',
          'Mingora',
          'Kohat',
          'Dera Ismail Khan',
        ];
      case 'Balochistan':
        return [
          'Quetta',
          'Gwadar',
          'Turbat',
          'Sibi',
          'Loralai',
        ];
      default:
        return [];
    }
  }
}